name: dro_health
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_svg: ^0.19.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/medications/
    - assets/images/logos/
    - assets/images/others/

  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/Proxima-Nova-Regular.otf
        - asset: assets/fonts/Proxima-Nova-Bold.otf
          weight: 700
        - asset: assets/fonts/Proxima-Nova-ExtraBold.otf
          weight: 900
